---
- hosts: all
  remote_user: steamstick
  tasks:
  - name: Install npm
    package:
      name: npm
      state: present

  - name: Start npm server
    command: npm start
    args:
      chdir: /home/steamstick